apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops14finalproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/David-Yashenko/DevSecOps14FinalProject.git"
    targetRevision: HEAD
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: myapp
  syncPolicy:
    syncPolicy:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
