apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: DevSecOps14FinalProject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/David-Yashenko/DevSecOps14FinalProject"
    targetRevision: HEAD
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
