version: '3.8'
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5001/api
    depends_on:
      - backend
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./Backend
    ports:
      - "5001:5001"
    volumes:
      - ./Backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mynetwork:
    driver: bridge
