version: '3.8'
services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./Backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
