name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version
        id: vars
        run: |
          COMMIT_SHA=${{ github.sha }}
          SHORT_SHA=${COMMIT_SHA: -7}
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Extract Image IDs
        run: |
          FRONTEND_IMAGE_ID=$(docker inspect --format='{{.Id}}' $(docker-compose images -q frontend))
          BACKEND_IMAGE_ID=$(docker inspect --format='{{.Id}}' $(docker-compose images -q backend))
          echo "FRONTEND_IMAGE_ID=${FRONTEND_IMAGE_ID}" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_ID=${BACKEND_IMAGE_ID}" >> $GITHUB_ENV

      - name: Tag and Push Docker Images
        run: |
          SHORT_SHA=${{ env.SHORT_SHA }}
          FRONTEND_IMAGE_ID=${{ env.FRONTEND_IMAGE_ID }}
          BACKEND_IMAGE_ID=${{ env.BACKEND_IMAGE_ID }}

          # Tagging and pushing frontend image
          docker tag $FRONTEND_IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$SHORT_SHA
          docker tag $FRONTEND_IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest

          # Tagging and pushing backend image
          docker tag $BACKEND_IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$SHORT_SHA
          docker tag $BACKEND_IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
