name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
          # Wait for the frontend service to be ready
          echo "Waiting for frontend service to be healthy..."
          sleep 30  # Adjust the sleep time as necessary
          # Check the frontend service by making a curl request
          FRONTEND_URL="http://localhost:80"
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null $FRONTEND_URL)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Frontend service did not return 200. Exiting..."
            exit 1
          fi
          echo "Frontend service is up and returned 200."
          docker-compose down

      - name: Tag and Push Docker Images
        run: |
          # Tagging frontend image
          docker tag devsecops14finalproject_frontend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest
          # Tagging backend image
          docker tag devsecops14finalproject_backend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
          # Pushing frontend image
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest
          # Pushing backend image
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
