name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version
        id: vars
        run: |
          COMMIT_SHA=${{ github.sha }}
          SHORT_SHA=${COMMIT_SHA:0:7}
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
          echo "Waiting for frontend service to be healthy..."
          sleep 30
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}\n" -X POST "http://localhost/api/check" -H "Content-Type: application/json" -d '{"nm":"david yashenko"}')
          if [ "$RESPONSE" -ne 200 ]; then
            echo "post request did not return 200. Exiting..."
            exit 1
          fi
          echo "frontend service is up and post request returned 200."
          docker-compose down

      - name: Tag and Push Docker Images
        run: |
          SHORT_SHA=${{ env.SHORT_SHA }}

          # Tagging and pushing frontend image
          docker tag devsecops14finalproject_frontend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$SHORT_SHA
          docker tag devsecops14finalproject_frontend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:latest

          # Tagging and pushing backend image
          docker tag devsecops14finalproject_backend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$SHORT_SHA
          docker tag devsecops14finalproject_backend ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:latest
