name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version
        id: vars
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
          echo "Waiting for frontend service to be healthy..."
          sleep 30
          FRONTEND_URL="http://localhost:80"
          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null $FRONTEND_URL)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Frontend service did not return 200. Exiting..."
            exit 1
          fi
          echo "Frontend service is up and returned 200."
          docker-compose down

      - name: Tag and Push Docker Images
        run: |
          COMMIT_SHA=${{ env.COMMIT_SHA }}
          FRONTEND_IMAGE=$(docker-compose images -q frontend)
          BACKEND_IMAGE=$(docker-compose images -q backend)

          docker tag $FRONTEND_IMAGE ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$COMMIT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_frontend:$COMMIT_SHA

          docker tag $BACKEND_IMAGE ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$COMMIT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops14finalproject_backend:$COMMIT_SHA
