name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
          # Wait for the services to be healthy
          docker-compose ps
          # Check the health of the backend service
          until [ "`docker inspect -f {{.State.Health.Status}} devsecops14finalproject_backend_1`" == "healthy" ]; do
            echo "Waiting for backend service to be healthy..."
            sleep 5
          done
          # Check the health of the frontend service
          until [ "`docker inspect -f {{.State.Health.Status}} devsecops14finalproject_frontend_1`" == "healthy" ]; do
            echo "Waiting for frontend service to be healthy..."
            sleep 5
          done
          # Optional: Make HTTP requests to verify the services are working
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:5001 || exit 1
          docker-compose down
          # Push images to Docker Hub
          docker-compose push
